### ISSUE TITLE
Z axis value incorrect

### ISSUE THREAD

**Issue by Pieloth** [AIRLegend/aitrack#172]
AItrack 0.7.0-alpha and Opentrack 2022.3.0, with Logitech C920 cam

**The Z value reported into Opentrack seems incorrect by a factor of 10**

When I stand at about 70cm from my webcam, Z is -6
When I go closer to the webcam, the Z value decrements towards 0
This does not happen for X and Y, when I move my head, X and Y seems to report correct values in cm

Maybe a missing multiplying factor for Z ?

Thanks for your help

Nicolas

**Comment by AIRLegend** [comment]
Yeah, the scale is lower than before for the Z axis. However, this should be fixable via the curves within Opentrack. Simply change the Max range for the Z axis and you're should be good to go.

![](https://user-images.githubusercontent.com/9653892/189712344-b728f14d-e534-4874-93d4-cd65f3848b83.png)

**Comment by Pieloth** [comment]
Thanks for your reply
That's actually what I did to workaroud, but was wondering if this was intentional, to have lowered the Z axis scale, or is it something to fix?

**Comment by BoomerGunship** [comment]
Love the better tracking accuracy in version 0.7.0!

Unfortunately, it seems I'm also facing this issue with the Z-axis. Previously on 0.6.6, the "Raw data tracker" on Opentrack starts at "-60" on the Z-axis, and moves up to ~"-40" when I get closer to the screen. 
But on 0.7.0, it starts at "-5", and only moves up to "-3" even when I get right up to my screen. Even setting the Max Input to 10cm doesn't really help, since it only detects 2 units in difference. This makes the Z-axis unusable, and now I could not look closely into the HUD or instruments when flying in DCS.

For now, I could workaround this by just manually zooming with the mouse's scroll wheel instead. Hoping there's a fix to this, since it's much easier and fun to look into the HUD/instruments through face tracking.

Cheers!

**Comment by AIRLegend** [comment]
Just removed Z scaling (https://github.com/AIRLegend/aitrack/commit/63349832e0c64254fa1ac9fa77179558f93a8aed). Will be out with the next release.

Closing as fixed :)
