### ISSUE TITLE
Support for IR cameras

### ISSUE THREAD

**Issue by cradle77** [AIRLegend/aitrack#50]
**Describe your idea**
IR cameras offer a better precision and resilience to environmental light when it comes to tracking facial features. I see them being mentioned in the main readme file, however I'm not sure if they are supported or how to activate them

I have a Logitech Brio but it only works with the normal camera

Would it be possible to support them?

**Comment by AIRLegend** [comment]
Hello! Thanks for suggesting new ideas! :) 

No, it's not possible at the moment as the tracker only works on simple RGB image features. In order to add IR support a full new neural network architecture (in addition to trainning it) would needed, and that just only for a few amount of cameras. That's not the idea of this tracker.

In the case a user already has an IR camera I think he'd woudln't be too far from a DIY TrackIR (or only buying/building the clip, which is cheap).
